/**
 * Created by jack on 16-8-17.
 */

const INIT_HOME_PAGE = 'INIT_HOME_PAGE';
const QUERY_POSTS_LIST = 'QUERY_POSTS_LIST';
const RECEIVE_POSTS_LIST = 'RECEIVE_POSTS_LIST';

export {
	INIT_HOME_PAGE,
	QUERY_POSTS_LIST,
	RECEIVE_POSTS_LIST
};
