/**
 * Created by jack on 16-8-17.
 */

const LOAD_NAV_LIST = 'LOAD_NAV_LIST';
const INIT_NAV_ELEMENT = 'INIT_NAV_ELEMENT';
const BODY_SCROLL_LISTENER_OF_NAV = 'BODY_SCROLL_LISTENER_OF_NAV';
const TOGGLE_NAV_SHOWN = 'TOGGLE_NAV_SHOWN';

export {
	LOAD_NAV_LIST,
	INIT_NAV_ELEMENT,
	BODY_SCROLL_LISTENER_OF_NAV,
	TOGGLE_NAV_SHOWN
};
